name: Build and deploy DTH:n uudet sivut

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout dockerfile
      uses: actions/checkout@v3

    - name: Checkout front
      uses: actions/checkout@v3
      with:
        repository: qlep/uusi-front
        path: uudistus-front

    - name: Checkout back
      uses: actions/checkout@v3
      with:
        repository: qlep/uusi-back
        path: uudistus-back

    - name: Login to Azure registry
      uses: azure/docker-login@v1
      with:
        login-server: https://uudistuscr.azurecr.io/
        username: ${{ secrets.AZURE_UUDISTUS_CR_USERNAME }}
        password: ${{ secrets.AZURE_UUDISTUS_CR_PASS }}
    
    - name: Build and Push to Azure CR
      run: |
          ls
          echo "FRONT DIR:"
          ls uudistus-front
          echo "BACK DIR:"
          ls uudistus-back
          docker build . -t uudistuscr.azurecr.io/dt-frontend-uudistus:uudest
          docker push uudistuscr.azurecr.io/dt-frontend-uudistus:uudest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: 'Deploy Container to Azure App Service'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'uudistus-dt'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_45361a6fe5644cecbf686cba95d083d1 }}
          images: 'uudistuscr.azurecr.io/dt-frontend-uudistus:uudest'
